spring:
  application:
    name: shierBISystem
  # 默认 dev 环境
  profiles:
    active: dev
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session 配置
  session:
    # todo 取消注释开启分布式 session（须先配置 Redis）
    # store-type: redis
    # 1 天过期
    timeout: 86400
  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shierbi
    username: root
    password: 123456
  # Redis 配置
  # todo 需替换配置，然后取消注释
  redis:
    database: 4
    host: localhost
    port: 6379
    timeout: 5000
    password: 123456
  # 文件上传
  servlet:
    multipart:
      # 大小限制
      max-file-size: 1MB
  # rabbitmq 信息
  rabbitmq:
    host: xxxxx
    password: xxx
    username: shier
    port: 5672
    listener:
      direct:
        acknowledge-mode: manual
server:
  address: 0.0.0.0
  port: 8103
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
# 对象存储
# todo 需替换配置
cos:
  client:
    accessKey: xxx
    secretKey: xxx
    region: xxx
    bucket: xxx
# 要使用的模型ID
ai:
  model:
    model-id: 1660100329896673281
# 鱼聪明SDK
yuapi:
  client:
    access-key: izvszyxh5ndyccuuhkxseft959h37idh
    secret-key: ktek1dp71r257jqfpx173nv98xzwpbi9
# todo 需替换配置
aliyun:
  oss:
    file:
      endpoint: xxxxxxxxxxxxx
      keyid: xxxxxxxxxxxxx
      keysecret: xxxxxxxxxxxxx
      bucketname: xxxxxxxxxxxxx